var tileSimbolo = {
	"X": "pasto_claro",
	"Y": "pasto_claro",
	"M": "bloque_muralla",
	".": "tierra",
	"P": "piedra",
	"R": "reja_horizontal_claro",
	"S": "reja_horizontal_claro",
	"F": "reja_abajo",
	"T": "reja_izquierda_claro",
	"U": "reja_izquierda_claro",
	"G": "reja_derecha_claro",
	"J": "reja_derecha_claro",
	"q": "reja_superior_izquierda",
	"w": "reja_superior_derecha",
	"a": "reja_inferior_izquierda",
	"s": "reja_inferior_derecha",
	"u": "reja_superior_izquierda_i",
	"i": "reja_superior_derecha_i",
	"j": "reja_inferior_izquierda_i",
	"k": "reja_inferior_derecha_i",
	"?": "missing_tile"
};